name: timer_pull
on:
  schedule:
    - cron: "5,10,15,25,35,45,55 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: |
        echo My name is P3TERX.
    - name: test git
      run: |
        git remote -v
