name: timer_pull
on:
  #schedule:
  #  - cron: "5,10,15,25,35,45,55 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  GITHUB_TOKEN: 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
jobs:

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hello World
      run: |
        echo My name is P3TERX.
    - name: test git
      run: |
       echo test git begin.
       git pull --unshallow
       git remote add origin-public https://github.com/sebaxakerhtc/rdpwrap.ini.git
       git fetch origin-public
       git merge --no-edit origin-public/master
       git remote set-url origin https://feng905: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@github.com/feng905/rdpwrap.ini
       echo $GITHUB_TOKEN
       git remote -v
       git pull
       git push 
       echo test git end.
       
