name: timer_pull
on:
  schedule:
    - cron: "*/30 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.RDPWRAP_TOKEN }}
jobs:

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hello World
      run: |
        echo My name is P3TERX.
    - name: check and pull latest rdpwrap.ini
      run: |
       echo test git begin.
       git pull --unshallow
       git remote add origin-public https://github.com/sebaxakerhtc/rdpwrap.ini.git
       git fetch origin-public
       git merge --no-edit origin-public/master
       git pull
       git push https://feng905:$GITHUB_TOKEN@github.com/feng905/rdpwrap.ini HEAD:master
       echo check and pull latest rdpwrap.ini end.
       
