# .github/workflows/sync.yml
name: Sync Fork

on:
  schedule:
    - cron: '5,10,15,25,35,45,55 * * * *' 
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: TG908/fork-sync@v1.6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: sebaxakerhtc # fork 的上游仓库 user
          head: master # fork 的上游仓库 branch
          base: master # 本地仓库 branch
