name: Sync-Fork2

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          base: master 
          head: master 
